### ISSUE TITLE
Executing ‘ll’ on a remote directory on an NFS client causes a core dump on the NFS server.

### ISSUE THREAD

**Issue by jcbmao** [bdzwillo/wrapfs_nfs#2]
1.On the NFS server,mounting wrapfs using the command “mount -t wrapfs /home/test /home/test”
2. On the NFS server, run `echo "/home/test *(rw,no_root_squash)" >> /etc/exports`, then execute `exportfs -rv`.
3. On the client, run `mount -t nfs 192.168.1.10:/home/test /mnt/test`.
4. On the client, run `ll /mnt/test`, and on the server, view the core dump in `dmesg`, the stack trace is as follows:
![image](https://github.com/bdzwillo/wrapfs_nfs/assets/31231441/f38552f8-2dae-4e2f-aedb-14ac3c709ae4)

nfs server kernel version: 4.19.90
nfs client kernel version: 3.10.0
What could be the issue?

**Comment by bdzwillo** [comment]
Thank you for the report. This happened when an inode was not found for the nfs filehandle mapping. The crash is fixed now, but the nfs export works only for underlying filesystems with the same filehandle layout. For xfs with 64-bit inodes the operation will fail and return a stale filehandle.

The nfs export support was just copied from the original wrapfs and never tested. The original version has the same issue.

**Comment by jcbmao** [comment]
Will data loss occur when mounting wrapfs if the filesystem has a large amount of write IO?

**Comment by bdzwillo** [comment]
No - none that I am aware of. Since writes are synchronous and no buffering occurs there will just be a little cpu overhead for wrapfs operations..
