### ISSUE TITLE
compile error on the 3.10.0-862.el7 kernel version

### ISSUE THREAD

**Issue by jcbmao** [bdzwillo/wrapfs_nfs#4]
Hi,the d_instantiate_new function is not defined in the wrapfs_interpose function in the lookup.c file when compiling the wrapfs module on the 3.10.0-862.el7 kernel version. how to fix it.

**Comment by bdzwillo** [comment]
The d_instantiate_new function was introduced in kernel 4.17, and redhat backported in to the el7 kernel.
See: https://github.com/torvalds/linux/commit/1e2e547a93a00ebc21582c06ca3c6cfea2a309ee (do d_instantiate/unlock_new_inode combinations safely)
It should work to simply substitute d_instantiate_new() by d_instantiate() followed by unlock_new_inode() like visible in the kernel patch.
