### ISSUE TITLE
the size reported by “du” is incorrect

### ISSUE THREAD

**Issue by jcbmao** [bdzwillo/wrapfs_nfs#5]
The file sizes in the “warpfs” directory are all 0 when using the “du” command,What is the reason for this issue?
After applying the patch below, “du” is correct.
![image](https://github.com/bdzwillo/wrapfs_nfs/assets/31231441/24fe5cad-fc50-4ada-8ba3-3fbbf2450f05)

**Comment by bdzwillo** [comment]
Thank you for the bug report. The getattr blocks info was not copied correctly when the underlying filesystem is not a remote filesystem like nfs. This is fixed now.
